# Generated by Django 5.2.7 on 2025-10-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='cust_name',
            field=models.CharField(default='ss', max_length=100),
            preserve_default=False,
        ),
    ]
