# Generated by Django 5.2.7 on 2025-10-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_customerprofile_cust_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
