# Generated by Django 5.2.7 on 2025-10-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicerequest_actual_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
