# Generated by Django 5.2.7 on 2025-10-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_servicerequest_preferred_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
