# Generated by Django 5.2.7 on 2025-10-22 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_servicerequest_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='title',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_requests', to='service.companyprofile'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to='service.customerprofile'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='service.servicetype'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_requests', to='service.technicianprofile'),
        ),
    ]
