# Generated by Django 5.2.7 on 2025-10-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_servicerequest_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
