# Generated by Django 5.2.7 on 2025-10-22 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_servicerequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_technicians', to='service.companyprofile'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='service_types',
            field=models.ManyToManyField(related_name='service_technicians', to='service.servicetype'),
        ),
    ]
