# Generated by Django 5.2.7 on 2025-10-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_technicianprofile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
