# Generated by Django 5.2.7 on 2025-10-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('Proceeding', 'Proceeding'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
