# Generated by Django 5.2.7 on 2025-10-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_servicerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], default='available', max_length=10),
        ),
    ]
