# Generated by Django 5.2.7 on 2025-11-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_remove_technicianprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='extra_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
