# Generated by Django 5.2.7 on 2025-11-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_servicerequest_extra_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
